[package]
name = "PANIKBUTTON"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
base64 = "0.22.1"
dotenv = "0.15.0"
lettre = "0.11.15"
tera = "1.20.0"
tokio = { version = "1.44.1", features = ["full"] }
tower-http = { version = "0.6.2", features = ["fs"] }
